mybatis:
  mapper-locations: classpath:mappers/*.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hr?useUnicode=true&characterEncoding=utf8
    password: 1234
    username: root
    driver-class-name: com.mysql.jdbc.Driver


# jwt配置盐和超时时间
JWT:
  secret: qwertyuiopasdfghjklzxcvbnmqwerty
  expire: 6000000
server:
  port: 8888